In [1]:
import numpy as np

docs = [
    'go india go strong and fearless',
    'india india rising with pride',
    'hip hip hurray the crowd goes wild',
    'jeetega bhai jeetega india jeetega again',
    'kohli kohli batting with passion',
    'dhoni dhoni calm mind sharp finish',
    'inquilab zindabad echoes through generations'
]


In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(oov_token='<embeddings>')

In [3]:
tokenizer.fit_on_texts(docs)

In [6]:
tokenizer.word_index

{'<embeddings>': 1,
 'india': 2,
 'jeetega': 3,
 'go': 4,
 'with': 5,
 'hip': 6,
 'kohli': 7,
 'dhoni': 8,
 'strong': 9,
 'and': 10,
 'fearless': 11,
 'rising': 12,
 'pride': 13,
 'hurray': 14,
 'the': 15,
 'crowd': 16,
 'goes': 17,
 'wild': 18,
 'bhai': 19,
 'again': 20,
 'batting': 21,
 'passion': 22,
 'calm': 23,
 'mind': 24,
 'sharp': 25,
 'finish': 26,
 'inquilab': 27,
 'zindabad': 28,
 'echoes': 29,
 'through': 30,
 'generations': 31}

In [5]:
len(tokenizer.word_index)

31

In [7]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[4, 2, 4, 9, 10, 11],
 [2, 2, 12, 5, 13],
 [6, 6, 14, 15, 16, 17, 18],
 [3, 19, 3, 2, 3, 20],
 [7, 7, 21, 5, 22],
 [8, 8, 23, 24, 25, 26],
 [27, 28, 29, 30, 31]]

In [8]:
from keras.utils import pad_sequences

In [9]:
sequences = pad_sequences(sequences, padding='post')

In [10]:
sequences

array([[ 4,  2,  4,  9, 10, 11,  0],
       [ 2,  2, 12,  5, 13,  0,  0],
       [ 6,  6, 14, 15, 16, 17, 18],
       [ 3, 19,  3,  2,  3, 20,  0],
       [ 7,  7, 21,  5, 22,  0,  0],
       [ 8,  8, 23, 24, 25, 26,  0],
       [27, 28, 29, 30, 31,  0,  0]], dtype=int32)

In [11]:
sequences.shape

(7, 7)

In [12]:
from keras.datasets import imdb
from keras import Sequential
from keras.layers import Dense, SimpleRNN, Flatten, Embedding

In [16]:
model = Sequential()
model.add(Embedding(31, output_dim=2, input_length=7))
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.compile('adam','accuracy')

In [19]:
pred = model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 915ms/step
[[[ 0.00170923  0.03103096]
  [-0.0034269   0.04043982]
  [ 0.00170923  0.03103096]
  [ 0.04312846 -0.00252205]
  [ 0.0364475  -0.03975512]
  [-0.02260572 -0.03953247]
  [ 0.02214768  0.00828241]]

 [[-0.0034269   0.04043982]
  [-0.0034269   0.04043982]
  [-0.04430473 -0.03502587]
  [-0.04444811 -0.03252556]
  [-0.00257174 -0.02108532]
  [ 0.02214768  0.00828241]
  [ 0.02214768  0.00828241]]

 [[ 0.00195011  0.02099318]
  [ 0.00195011  0.02099318]
  [-0.03996787  0.04508379]
  [ 0.03069318  0.04960218]
  [-0.0234116  -0.00021476]
  [-0.0234116  -0.00021476]
  [-0.0234116  -0.00021476]]

 [[-0.03015238 -0.04909107]
  [-0.0234116  -0.00021476]
  [-0.03015238 -0.04909107]
  [-0.0034269   0.04043982]
  [-0.03015238 -0.04909107]
  [-0.0234116  -0.00021476]
  [ 0.02214768  0.00828241]]

 [[-0.04430617 -0.03059106]
  [-0.04430617 -0.03059106]
  [-0.0234116  -0.00021476]
  [-0.04444811 -0.03252556]
  [-0.0234116  -0.00021476]
  [ 0.02214768  0.00828241]
 

**IMDb Dataset**

In [20]:
(X_train, y_train), (X_test, y_test) = imdb.load_data()

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step


In [21]:
X_train.shape

(25000,)

In [22]:
print(len(X_train[0]))
print(len(X_train[1]))
print(len(X_train[2]))

218
189
141


In [23]:
y_train.shape

(25000,)

In [24]:
X_train = pad_sequences(X_train, padding='post', maxlen=100)
X_test = pad_sequences(X_test, padding='post', maxlen=100)

In [25]:
X_train.shape

(25000, 100)

In [26]:
print(len(X_train[0]))
print(len(X_train[1]))
print(len(X_train[2]))

100
100
100


In [31]:
model = Sequential()

model.add(Embedding(10000, 2, input_length=100))
model.add(SimpleRNN(32, return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [32]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Epoch 1/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 14s 14ms/step - accuracy: 0.5332 - loss: 0.6868 - val_accuracy: 0.7783 - val_loss: 0.4878
Epoch 2/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.7968 - loss: 0.4551 - val_accuracy: 0.8310 - val_loss: 0.3873
Epoch 3/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.8616 - loss: 0.3390 - val_accuracy: 0.7932 - val_loss: 0.4212
Epoch 4/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.8941 - loss: 0.2747 - val_accuracy: 0.8396 - val_loss: 0.3943
Epoch 5/5
782/782 ━━━━━━━━━━━━━━━━━━━━ 9s 11ms/step - accuracy: 0.9130 - loss: 0.2340 - val_accuracy: 0.8240 - val_loss: 0.4049
